# Out of the scope:
# TGLANG_LANGUAGE_FUNC
# TGLANG_LANGUAGE_TL

import requests
import json
import tqdm
import re
import os


def extract_code(text):
    code_blocks = re.findall(r"```.*?```", text, re.DOTALL)
    if not code_blocks:
        return None

    code_blocks = code_blocks[0]
    code_blocks = code_blocks.splitlines()
    code_blocks = "\n".join(code_blocks[1:-1])
    return code_blocks


def ask_llama(prompt, context=None):
    url = "http://localhost:11434/api/generate"

    req = {"model": "llama2", "stream": False, "prompt": prompt}
    if context is not None:
        req["context"] = context

    while True:
        try:
            response = requests.request(
                "POST", url, data=json.dumps(req), timeout=60
            ).json()
            break
        except:
            continue

    return response["response"], response["context"]


def get_code(
    lang,
    use_tasks=True,
    use_base=True,
    repeat_base=20,
    reset_context=4,
    limit=None,
    save_root=None,
):
    lang_name, hint, task = languages[lang]

    all_requests = []
    if use_tasks:
        for task in tasks[task]:
            request = [
                base_prompt_task.replace("<task>", task)
                .replace("<lang>", lang_name)
                .replace("<hint>", hint)
            ]
            for more_prompt in more_prompts_task:
                request.append(more_prompt)
            all_requests.append(request)
    if use_base:
        prompt = base_prompt_general.replace("<lang>", lang_name).replace(
            "<hint>", hint
        )
        request = [prompt]
        for _ in range(repeat_base):
            request.append(prompt)
        all_requests.append(request)

    if limit is not None:
        all_requests = all_requests[:limit]

    code_blocks = []

    if save_root is not None:
        save_dir = os.path.join(save_root, lang)
        os.makedirs(save_dir, exist_ok=True)

    for i, request in enumerate(
        tqdm.tqdm(all_requests, desc="Processing language '%s'" % lang_name)
    ):
        if save_root is not None:
            request_save_dir = os.path.join(save_dir, str(i))
            if os.path.exists(request_save_dir) and len(
                os.listdir(request_save_dir)
            ) == len(request):
                continue

            os.makedirs(request_save_dir, exist_ok=True)

        context = None
        for j, prompt in enumerate(request):
            if j % reset_context == 0:
                context = None
            response, curr_context = ask_llama(prompt, context)
            context = curr_context

            code = extract_code(response)
            if code is None:
                continue
            code_blocks.append(code)

            if save_root is not None:
                with open(os.path.join(request_save_dir, "%d.txt" % j), "w") as f:
                    f.write(code)

    return code_blocks


base_prompt_general = """
    We are writing dataset for programming language identification.
    Write me example of <lang> language and use rare language specific features.
    Not necessary to make it work. Just write a code that looks like a real code <hint>.
    Wrap the code in a ```code block```. Provide the only one code block in your answer.
    Write just a code without explanation and make it very natural.
    DON'T USE COMMENTS IN THE CODE. DON'T COMMENT THE CODE.
"""

more_prompt_general = """
    DON'T REPEAT EXAMPLES ABOVE!
    give me another example which show rare language features and doesn't look like a previous example!
    Write just a code without explanation and make it very natural.
    DON'T USE COMMENTS IN THE CODE. DON'T COMMENT THE CODE.
"""

base_prompt_task = """
    <task>
    Use <lang> language and use rare language specific features.
    Not necessary to make it work. Just write a code that looks like a real <lang> code <hint>.
    Wrap the code in a ```code block```. Provide the only one code block in your answer.
    Write just a code without explanation and make it very natural.
    DON'T USE COMMENTS IN THE CODE. DON'T COMMENT THE CODE.
"""

more_prompts_task = [
    "Rewrite it and make it as short as possible. Use language specific features",
]

languages = {
    # programs
    "C": ["C", "(and it is clear that this is not C++)", "programs"],
    "C++": ["C++", "(and it is clear that this is not C)", "programs"],
    "Java": ["Java", "", "programs"],
    "C#": ["C#", "", "programs"],
    "Objective-C": ["Objective-C", "", "programs"],
    "Python": ["Python", "", "programs"],
    "Ruby": ["Ruby", "", "programs"],
    "PHP": ["PHP", "(and it is clear that this is not Hack language)", "programs"],
    "JavaScript": [
        "JavaScript",
        "(and it is clear that this is not TypeScript)",
        "programs",
    ],
    "TypeScript": [
        "TypeScript",
        "(and it is clear that this is not JavaScript). USE TYPESCRIPT SPECIFIC DEFENITIONS (:type), CLASSES AND ENUMS.",
        "programs",
    ],
    "Go": ["Go", "", "programs"],
    "Rust": ["Rust", "", "programs"],
    "Lua": ["Lua", "", "programs"],
    "Swift": ["Swift", "", "programs"],
    "Kotlin": ["Kotlin", "", "programs"],
    "Dart": ["Dart", "", "programs"],
    "JSON": ["JSON", "", "structures"],
    "XML": ["XML", "", "structures"],
    "HTML": ["HTML", "", "markup"],
    "Shell": ["Bash", "", "scripts"],
    "PowerShell": ["PowerShell", "", "scripts"],
    "CSS": ["CSS", "", "css"],
    "SQL": ["SQL", "", "database"],
    "Docker": ["Docker", "", "docker"],
    "NGINX": ["NGINX Config", "", "nginx"],
    "Solidity": ["Solidity", "", "blockchain"],
}

tasks = {
    "programs": [
        "Create a program that calculates the factorial of a number.",
        "Develop a script to scrape web data and store it in a CSV file.",
        "Write a function to sort an array of integers using quicksort algorithm.",
        "Implement a basic calculator that performs addition, subtraction, multiplication, and division.",
        "Build a REST API to manage a simple contact list (create, read, update, delete).",
        "Design a chatbot that can answer predefined questions.",
        "Develop a program that detects and corrects spelling mistakes in a text file.",
        "Create a script to convert images from JPG to PNG format.",
        "Write a program to solve Sudoku puzzles.",
        "Implement a blockchain ledger for recording transactions.",
        "Build a command-line tool to track personal expenses and generate monthly reports.",
        "Design a simple web crawler that indexes the titles of webpages.",
        "Develop a program that simulates a rolling dice game.",
        "Create a GUI-based application to manage a digital library of books.",
        "Implement a basic text editor with features like open, save, and edit.",
        "Write a program that performs image resizing and cropping.",
        "Develop a weather forecasting application that uses an external API.",
        "Create a tool for visualizing data from a CSV file in a bar chart.",
        "Implement a system for encrypting and decrypting text messages.",
        "Write a program that generates and verifies digital signatures.",
        "Develop a flight booking system with options to book, cancel, and view bookings.",
        "Create a memory game with a graphical user interface.",
        "Implement a program for real-time currency conversion using live exchange rates.",
        "Write a script to automate backup of files to a cloud storage service.",
        "Develop a tic-tac-toe game that can be played in the console.",
        "Create a program that can parse and display RSS feeds.",
        "Implement a voice recognition system that executes basic commands.",
        "Build a system to analyze and plot stock market trends.",
        "Write a program that compresses and decompresses files.",
        "Develop a peer-to-peer file sharing application.",
        "Create a blog platform with features like post creation, editing, and commenting.",
        "Implement a pathfinding algorithm for navigation in a grid.",
        "Build a program that tracks the position of objects in real-time video feed.",
        "Write a script for automated email sending with attachment support.",
        "Develop a system for managing a small hotel's reservations and check-ins.",
        "Create a tool for audio file processing and effects application.",
        "Implement a facial recognition system for security purposes.",
        "Write a program for real-time chat communication over a network.",
        "Develop an interactive map for a virtual tour of a museum.",
        "Create a fitness tracker app that records steps, distance, and calories burned.",
        "Implement an AI-based recommendation system for e-commerce.",
        "Implement the A* pathfinding algorithm for a grid-based game.",
        "Create a program that simulates the Towers of Hanoi puzzle using recursive functions.",
        "Write a program that uses dynamic programming to solve the Knapsack problem.",
        "Develop a script that uses regular expressions to validate email addresses.",
        "Implement a binary search tree with insert, delete, and search operations.",
        "Create a program that uses decorators or similar constructs for caching function outputs.",
        "Write a Dijkstra's algorithm implementation for finding the shortest path in a graph.",
        "Develop a program that simulates particle collision physics.",
        "Implement a genetic algorithm for optimizing a simple function.",
        "Create a custom memory allocator.",
        "Write a program that performs matrix operations using operator overloading.",
        "Develop a concurrent web scraper that uses threading or async features.",
        "Implement an LRU (Least Recently Used) cache system.",
        "Create a program that uses bitwise operations for efficient data manipulation.",
        "Write a bubble sort algorithm and optimize it using low-level optimizations.",
        "Develop a program that uses lambda functions to manipulate collections of data.",
        "Implement a command-line tool that uses subcommands and flags (like git or docker).",
        "Create a neural network from scratch for a simple classification task.",
        "Write an interpreter for a simple custom scripting language.",
        "Develop a multithreaded server that can handle multiple client connections simultaneously.",
        "Implement the RSA algorithm for encryption and decryption of text.",
        "Create a program that generates fractals using recursion.",
        "Write a merge sort algorithm and explain its time complexity.",
        "Develop a program that demonstrates the use of polymorphism in object-oriented programming.",
        "Implement a command-line based Tetris game.",
        "Create a ray tracer to render 3D scenes.",
        "Write a program that uses graph algorithms to analyze social network connections.",
        "Develop a program that demonstrates the use of closures in functional programming.",
        "Implement a program that uses SIMD (Single Instruction, Multiple Data) instructions for performance optimization.",
        "Create a domain-specific language for a specific application and write an interpreter for it.",
        "Write a program that performs audio signal processing and visualizes the waveforms.",
        "Develop a blockchain-based simple voting system.",
        "Implement a program that performs natural language processing to summarize text.",
        "Create an augmented reality application that can overlay virtual objects in a real environment.",
        "Write a program to simulate the behavior of cellular automata like Conway's Game of Life.",
        "Develop a machine learning model to predict stock prices based on historical data.",
        "Implement a program that uses the Monte Carlo method for numerical integration.",
        "Create a program that implements a custom compression algorithm.",
        "Write a program that uses metaprogramming techniques for code generation.",
        "Develop a cross-platform mobile app that can track fitness activities.",
        "Write a function to reverse a string.",
        "Create a class that represents a geometric shape with methods to calculate area and perimeter.",
        "Implement a function that recursively calculates Fibonacci numbers.",
        "Develop a snippet to connect to a database and perform a simple query.",
        "Write a regular expression to match valid IP addresses.",
        "Create a function that sorts a list of names alphabetically.",
        "Implement a decorator function that times the execution of another function.",
        "Write a snippet to read and parse a JSON file.",
        "Develop a function to check if a number is prime.",
        "Create a lambda function for a simple arithmetic operation, like adding two numbers.",
        "Implement a function to merge two sorted arrays into one sorted array.",
        "Write a snippet that demonstrates exception handling for file operations.",
        "Develop a regular expression to validate date formats (e.g., DD/MM/YYYY).",
        "Create a function that performs a binary search on a sorted array.",
        "Implement a snippet to generate a random password with specific criteria (length, characters used).",
        "Write a function that converts temperature from Celsius to Fahrenheit and vice versa.",
        "Develop a fragment that creates and manipulates a multidimensional array.",
        "Create a snippet to demonstrate how to use map/filter/reduce functions on a collection.",
        "Implement a function to check if a string is a palindrome.",
        "Write a snippet to demonstrate the use of closures in your chosen programming language.",
        "Develop a function to calculate the mean, median, and mode of a set of numbers.",
        "Create a snippet to demonstrate the use of async/await for handling asynchronous operations.",
        "Implement a function that simulates a dice roll using random number generation.",
        "Write a regular expression to extract all email addresses from a text.",
        "Develop a snippet to demonstrate polymorphism in object-oriented programming.",
        "Create a function that encrypts a string using a simple cipher (like Caesar cipher).",
        "Implement a snippet that creates a simple GUI window with a button and a text label.",
        "Write a function to check the balance of parentheses in an expression.",
        "Develop a snippet to stream data from an online API and print it.",
        "Create a function to find the longest word in a sentence.",
        "Implement a snippet to manipulate image data, like changing brightness or contrast.",
        "Write a regular expression for parsing log files with a specific format.",
        "Develop a fragment that demonstrates the use of threading or multiprocessing.",
        "Create a function to convert a binary number to decimal and vice versa.",
        "Implement a snippet that plays a simple sound file.",
        "Write a function to implement a basic text search in a string.",
        "Develop a snippet to visualize data using a plotting library (like matplotlib or seaborn).",
        "Create a function to calculate the distance between two points in a coordinate system.",
        "Implement a snippet to handle keyboard or mouse input events.",
        "Write a code snippet that uses a list comprehension to create a list of squares of the first 10 integers.",
        "Create a snippet that uses a generator expression to iterate over and print the Fibonacci sequence up to a certain number.",
        "Develop a code block that demonstrates the use of bitwise operators to toggle the bits of a number.",
        "Write a code snippet to demonstrate tuple unpacking in a loop over a list of tuples.",
        "Implement a snippet that uses a language's unique collection datatype (like a set in Python or a dictionary in JavaScript) in a creative way.",
        "Create a code block that demonstrates the use of a language-specific feature for error handling, like Python's try-except-else construct.",
        "Develop a snippet to showcase the use of conditional expressions in a single line of code.",
        "Write a code block that manipulates strings using a language's advanced string formatting or manipulation features.",
        "Create a snippet that uses a rare or underutilized data structure provided by the language's standard library.",
        "Develop a code block that demonstrates the use of inline assembly within a high-level language, if supported.",
        "Write a snippet to showcase pattern matching or destructuring, if the language supports it.",
        "Implement a code block that demonstrates the use of language-specific preprocessor directives or compiler flags.",
        "Create a snippet that uses a functional programming feature like currying or partial function application.",
        "Develop a snippet to showcase the use of a language's macro system, if available.",
        "Write a code block that demonstrates a unique concurrency feature of the language, like goroutines in Go or async/await in JavaScript.",
        "Implement a snippet that manipulates an array or list using advanced slicing or indexing.",
        "Create a code block that uses a unique file I/O feature of the language.",
        "Develop a snippet to demonstrate the use of custom iterators or generators, if the language supports them.",
        "Write a code block that showcases the language's capabilities for metaprogramming or reflection.",
        "Create a snippet that demonstrates the use of a language-specific library for graphics or sound processing.",
        "Develop a code block to demonstrate the use of advanced mathematical functions or complex number operations in the language.",
        "Write a snippet that shows how to use language-specific syntax for parallel or GPU computing.",
        "Implement a code block that showcases the use of language extensions or optional features that are not part of the standard library.",
        "Create a snippet to demonstrate language-specific debugging or profiling tools.",
        "Develop a code block that uses a unique language feature for working with dates and times.",
        "Write a snippet that demonstrates the use of a language-specific feature for network programming.",
        "Create a code block that showcases the use of embedded domain-specific languages (DSLs) within the programming language.",
        "Develop a snippet to demonstrate the language's unique approach to memory management or garbage collection.",
        "Write a code block that uses advanced type system features like generics, type inference, or type coercion.",
        "Implement a snippet that showcases the language's support for internationalization and localization.",
    ],
    ### Shell, PowerShell
    "scripts": [
        "Script a solution to merge several CSV files into one, ensuring duplicate rows are removed.",
        "Write a command to recursively search for a text string in all files within a directory, ignoring case.",
        "Demonstrate a script that sets up a cron job or scheduled task to run every Monday at 8 AM.",
        "Create a script to monitor a specific directory for file changes and log these changes.",
        "Show how to write a script that reads a configuration file and sets environment variables based on its contents.",
        "Write a script to automate the process of SSHing into a list of servers and executing a given command.",
        "Describe a complex pipeline that sorts, deduplicates, and counts unique lines from a text stream.",
        "Write a script that uses regular expressions to validate email addresses from a text file.",
        "Demonstrate how to set up a menu-driven script with multiple options for different operations.",
        "Create a command to batch convert images from one format to another.",
        "Script a solution to compare two directories and report differences in file content.",
        "Show how to script a complex SQL query execution and result processing.",
        "Write a script that encrypts and decrypts files using a specific encryption method.",
        "Demonstrate a script that interacts with an API and processes the JSON response.",
        "Create a script to automate system health checks, reporting any anomalies found.",
        "Show how to write a script that parses and formats log files into a human-readable report.",
        "Write a script that dynamically generates another script based on user input.",
        "Describe a script that uses associative arrays to store and manipulate data.",
        "Script a solution to track and report file system usage over time.",
        "Show how to write a script that handles multiple simultaneous network connections.",
        "Write a script that integrates with a version control system to automate code deployments.",
        "Demonstrate a script that uses a complex function with multiple parameters and error handling.",
        "Create a script that automates data backup with verification and logging.",
        "Show how to script the installation and configuration of a web server with custom settings.",
        "Write a script to automate the testing of network ports and services on a server.",
        "Describe a script that uses recursion for file system operations.",
        "Script a solution for real-time monitoring of server logs for specific error patterns.",
        "Show how to write a script that automates database maintenance tasks.",
        "Write a script that uses a complex regex to reformat text files.",
        "Demonstrate a script that sets up a virtual environment for a specific programming project.",
        "Create a script to automate the process of user account creation and setup.",
        "Show how to write a script that compiles and runs code in multiple programming languages.",
        "Write a script that generates a network topology diagram from configuration files.",
        "Describe a script that automates the management of virtual machines.",
        "Script a solution to analyze disk usage and automatically clean up temporary files.",
        "Show how to write a script that integrates with cloud storage APIs.",
        "Write a script that manages firewall rules and monitors for security breaches.",
        "Demonstrate a script that performs bulk data migration between different databases.",
        "Create a script to manage software dependencies for a complex project.",
        "Show how to write a script that automates the generation of comprehensive system reports.",
        "Write a script to list all files in the current directory.",
        "Create a command to display the current date and time.",
        "How would you check the disk usage of a specified directory?",
        "Demonstrate how to find files modified in the last 24 hours.",
        "Show a command to download a file from the internet.",
        "Explain how to count the number of lines in a text file.",
        "Write a script to backup files to a specified directory.",
        "Describe how to extract the contents of a zip file.",
        "Create a command to display system information.",
        "How would you automate sending emails with an attachment?",
        "Write a script to rename a batch of files.",
        "Demonstrate how to parse JSON data from a file.",
        "Show a command to find the IP address of a host.",
        "Explain how to check the availability of a website.",
        "Write a script to monitor CPU and memory usage.",
        "Describe how to create a symbolic link to a file.",
        "Create a command to list all running processes.",
        "How would you compress multiple files into a tar archive?",
        "Write a script to synchronize a folder with a remote server.",
        "Demonstrate how to change file permissions.",
        "Show a command to display the history of executed commands.",
        "Explain how to set environment variables.",
        "Write a script to find duplicate files in a directory.",
        "Describe how to watch a log file for changes.",
        "Create a command to measure the execution time of a script.",
        "How would you list all installed packages on a system?",
        "Write a script to automate software installation.",
        "Demonstrate how to redirect output to a file.",
        "Show a command to check network connectivity.",
        "Explain how to schedule a task to run at regular intervals.",
        "Write a script to parse command-line arguments.",
        "Describe how to loop over files in a directory.",
        "Create a command to find the largest files in a directory.",
        "How would you check the status of a service?",
        "Write a script to automate database backups.",
        "Demonstrate how to split a large file into smaller parts.",
        "Show a command to compare the contents of two files.",
        "Explain how to search for a string in multiple files.",
        "Write a script to generate a report from log files.",
        "Describe how to automate system updates.",
        "Write a script to calculate the Fibonacci sequence up to the Nth number.",
        "Create a command to find and replace text in multiple files in a directory.",
        "Script a solution to calculate the factorial of a number.",
        "Show how to write a script that sorts a list of names alphabetically.",
        "Demonstrate a script that finds the greatest common divisor of two numbers.",
        "Write a script to check if a number is prime.",
        "Create a command to batch resize images in a directory.",
        "Script a solution to parse and display XML file content.",
        "Show how to write a script that backs up a database at regular intervals.",
        "Demonstrate a script that automates the creation of virtual network interfaces.",
        "Write a script to calculate the sum of numbers in a file.",
        "Create a command to list all users currently logged into the system.",
        "Script a solution to monitor file modifications and alert if specific patterns are found.",
        "Show how to write a script that automates the setup of a development environment.",
        "Demonstrate a script that automates the deployment of a web application.",
        "Write a script to implement a basic version of the 'grep' command.",
        "Create a command to display the amount of free disk space.",
        "Script a solution to synchronize files between two remote servers.",
        "Show how to write a script that calculates network bandwidth usage.",
        "Demonstrate a script that automates the provisioning of cloud resources.",
        "Write a script to implement a simple chat server.",
        "Create a command to monitor system temperature.",
        "Script a solution for a basic spell checker.",
        "Show how to write a script that automates the installation of a software stack.",
        "Demonstrate a script that performs load balancing between servers.",
        "Write a script to compress multiple directories into individual archives.",
        "Create a command to find all files with a specific extension and list their sizes.",
        "Script a solution to track system uptime and report any downtimes.",
        "Show how to write a script that automates DNS record updates.",
        "Demonstrate a script that analyzes web server logs for traffic patterns.",
        "Write a script to implement a basic web crawler.",
        "Create a command to batch rename files based on a pattern.",
        "Script a solution to check for broken links in a website.",
        "Show how to write a script that generates a sitemap for a website.",
        "Demonstrate a script that performs automated code linting.",
        "Write a script to automate the migration of user data between systems.",
        "Create a command to find the most frequently used commands in command history.",
        "Script a solution to convert audio files from one format to another.",
        "Show how to write a script that organizes files by date.",
        "Demonstrate a script that calculates disk I/O statistics.",
        "Write a script to implement a basic text-to-speech conversion.",
        "Create a command to display the top 10 most CPU-intensive processes.",
        "Script a solution to automate the management of SSL certificates.",
        "Show how to write a script that facilitates database replication.",
        "Demonstrate a script that sets up a secure tunnel to a remote server.",
        "Write a script to monitor the health of a website.",
        "Create a command to display real-time network traffic.",
        "Script a solution to batch process video files for encoding.",
        "Show how to write a script that extracts metadata from media files.",
        "Demonstrate a script that automates the configuration of a firewall.",
        "Write a script to set up a mail server.",
        "Create a command to generate a report of user activities.",
        "Script a solution to automate the archiving of old files.",
        "Show how to write a script that performs data encryption.",
        "Demonstrate a script that syncs files to a cloud storage service.",
    ],
    ### Solidity
    "blockchain": [
        "Write a Solidity smart contract for a simple token exchange.",
        "Develop a Solidity contract for a decentralized voting system.",
        "Create a Solidity function to transfer ERC20 tokens.",
        "Implement a Solidity smart contract for a crowdfunding platform.",
        "Outline a Solidity contract for a decentralized autonomous organization (DAO).",
        "Design a Solidity-based smart contract for a lottery game.",
        "Draft a Solidity function to check the balance of an Ethereum address.",
        "Compose a Solidity contract for a digital asset marketplace.",
        "Construct a Solidity contract for a decentralized finance (DeFi) application.",
        "Formulate a Solidity smart contract for a supply chain tracking system.",
        "Develop a Solidity function for a multi-signature wallet.",
        "Write a Solidity contract that integrates with an Oracle for external data.",
        "Create a Solidity contract for an NFT (Non-Fungible Token) collection.",
        "Draft a Solidity-based escrow service contract.",
        "Design a Solidity contract for a peer-to-peer lending platform.",
        "Implement a Solidity function to handle token staking.",
        "Outline a Solidity smart contract for an insurance application.",
        "Compose a Solidity contract for a real estate tokenization platform.",
        "Construct a Solidity function for a decentralized exchange (DEX).",
        "Formulate a Solidity contract for a gaming platform.",
        "Create a Solidity function to mint new tokens.",
        "Write a Solidity contract for a token airdrop mechanism.",
        "Develop a Solidity smart contract for a loyalty rewards program.",
        "Draft a Solidity function for token burning.",
        "Design a Solidity contract for an event ticketing system.",
        "Implement a Solidity smart contract for a legal contract automation.",
        "Outline a Solidity function for withdrawing funds from a contract.",
        "Compose a Solidity contract for a car sharing platform.",
        "Construct a Solidity contract for a decentralized social media platform.",
        "Formulate a Solidity function for automatic dividend distribution.",
        "Develop a Solidity smart contract for a digital identity verification system.",
        "Write a Solidity contract for a decentralized file storage solution.",
        "Create a Solidity contract for a blockchain-based voting system.",
        "Draft a Solidity function for a flash loan in DeFi.",
        "Design a Solidity contract for a decentralized job marketplace.",
        "Implement a Solidity smart contract for a time-locked wallet.",
        "Outline a Solidity function for a trust fund management system.",
        "Compose a Solidity contract for an energy trading platform.",
        "Construct a Solidity function for a decentralized content delivery network.",
        "Formulate a Solidity contract for a blockchain-based medical record system.",
        "Develop a Solidity contract using assembly blocks for low-level operations.",
        "Create a Solidity function implementing a custom modifier for access control.",
        "Write a Solidity contract that uses events for logging contract activities.",
        "Implement a proxy contract in Solidity for upgradable smart contracts.",
        "Design a Solidity contract using the 'delegatecall' function for library calls.",
        "Compose a Solidity function that handles Ethereum's gas optimization.",
        "Construct a Solidity contract with a fallback function for Ether transactions.",
        "Draft a Solidity contract using structs for complex data types.",
        "Formulate a Solidity function that employs bitwise operators.",
        "Develop a Solidity contract that integrates EIP-712 for typed message signing.",
        "Create a Solidity function for a contract that self-destructs after certain conditions.",
        "Write a Solidity contract with a circuit breaker pattern for emergency stops.",
        "Implement a re-entrancy guard in a Solidity smart contract.",
        "Design a Solidity contract utilizing the 'check-effects-interactions' pattern.",
        "Outline a Solidity contract that implements a state machine.",
        "Compose a Solidity function using cryptographic functions for security.",
        "Construct a Solidity contract with custom error handling using 'revert' statements.",
        "Develop a Solidity contract that optimizes storage layout for gas efficiency.",
        "Draft a Solidity function that uses inline assembly for custom EVM instructions.",
        "Design a Solidity contract employing the 'memory' and 'storage' data locations.",
        "Implement a payment splitter contract in Solidity with dynamic shares.",
        "Write a Solidity contract for atomic swaps between different cryptocurrencies.",
        "Create a Solidity contract that handles ERC-721 token metadata dynamically.",
        "Formulate a Solidity function for batch processing of transactions.",
        "Construct a Solidity contract using contract inheritance for modular code.",
        "Outline a Solidity contract that incorporates IPFS for decentralized storage.",
        "Compose a Solidity function to verify digital signatures.",
        "Develop a Solidity contract with a custom gas price oracle.",
        "Draft a Solidity function implementing recursive calling patterns.",
        "Design a Solidity contract for a decentralized autonomous initial coin offering (DAICO).",
        "Implement a Solidity contract that uses the 'immutable' keyword for constant values.",
        "Write a Solidity contract with a locking mechanism for token vesting.",
        "Create a Solidity contract that integrates with a Layer 2 scaling solution.",
        "Formulate a Solidity function for efficient batch token transfers.",
        "Construct a Solidity contract using libraries for shared logic.",
        "Develop a Solidity function for advanced mathematical computations using fixed-point arithmetic.",
        "Outline a Solidity contract with role-based permissions using 'AccessControl'.",
        "Compose a Solidity contract for a decentralized file encryption and sharing service.",
        "Implement a Solidity function that uses the 'payable' keyword for flexible payments.",
        "Design a Solidity contract that interacts with multiple ERC standards (e.g., ERC-20, ERC-721, ERC-1155).",
        "Show a Solidity snippet for defining a public uint variable.",
        "Write a Solidity line to emit an event with two parameters.",
        "Demonstrate how to declare an array in Solidity.",
        "Illustrate a function modifier in Solidity that checks a condition.",
        "Present a snippet for a Solidity mapping from address to uint.",
        "Write a line of Solidity code to safely add two numbers.",
        "Show how to define an enum in Solidity.",
        "Give an example of a Solidity struct with two fields.",
        "Demonstrate a Solidity function that returns its input incremented by one.",
        "Illustrate the use of the 'require' statement in Solidity.",
        "Show how to declare a Solidity event with an indexed parameter.",
        "Write a Solidity snippet to update the value of a state variable.",
        "Provide a Solidity example of a constructor function.",
        "Demonstrate a Solidity external function declaration.",
        "Illustrate a snippet for creating a new ERC20 token in Solidity.",
        "Show how to write a Solidity function that accepts Ether.",
        "Write a line in Solidity to check the balance of an address.",
        "Demonstrate a Solidity snippet for a read-only (view) function.",
        "Provide a Solidity example using the 'memory' keyword.",
        "Illustrate a Solidity function that emits an event.",
        "Show a Solidity snippet for a payable fallback function.",
        "Write a Solidity line for inheriting from another contract.",
        "Demonstrate how to use the 'selfdestruct' function in Solidity.",
        "Provide a snippet for a Solidity function with a for loop.",
        "Illustrate how to write a Solidity interface.",
        "Show how to define a fixed-size bytes array in Solidity.",
        "Write a Solidity line for a function that returns multiple values.",
        "Demonstrate a Solidity snippet using the 'revert' statement.",
        "Illustrate a Solidity public getter function for a private variable.",
        "Show a snippet for handling division in Solidity.",
        "Write a Solidity line for declaring a constant variable.",
        "Demonstrate how to use the 'pragma' directive in Solidity.",
        "Provide a Solidity example of a library function.",
        "Illustrate Solidity code for a mapping with a struct value.",
        "Show a Solidity snippet for interacting with another contract.",
        "Write a one-line Solidity function to transfer ERC20 tokens.",
        "Demonstrate a Solidity snippet to check if an address is a contract.",
        "Provide a snippet for a Solidity constructor with parameters.",
        "Illustrate how to use the 'override' keyword in Solidity.",
        "Show how to define a custom error in Solidity.",
    ],
    ### SQL
    "database": [
        "Write an SQL query to select all columns from a table named 'customers'.",
        "Create an SQL command to insert a new record into the 'employees' table.",
        "Generate an SQL statement to update the 'email' field of the 'users' table.",
        "Formulate an SQL query to delete records from the 'orders' table where the 'order_date' is before 2020.",
        "Compose an SQL command to create a new table called 'products' with columns for id, name, and price.",
        "Construct an SQL query to select the total number of entries in the 'sales' table.",
        "Design an SQL query to find the average price of all products in the 'products' table.",
        "Develop an SQL statement to list all distinct customer names from the 'customers' table.",
        "Draft an SQL command to add a new column named 'category' to the 'products' table.",
        "Form an SQL query to join the 'orders' table with the 'customers' table based on customer ID.",
        "Write an SQL query to find the highest and lowest salaries in the 'employees' table.",
        "Create an SQL statement to group records in the 'sales' table by month and calculate total sales per month.",
        "Generate an SQL command to alter the data type of the 'price' column in the 'products' table.",
        "Formulate an SQL query to select all records from the 'users' table where the name starts with 'A'.",
        "Compose an SQL statement to count the number of products in each category in the 'products' table.",
        "Construct an SQL query to list the top 10 most expensive products in the 'products' table.",
        "Design an SQL command to drop the 'archived_orders' table.",
        "Develop an SQL query to select customers from the 'customers' table who have made more than 5 orders.",
        "Draft an SQL command to rename the 'category' column to 'product_category' in the 'products' table.",
        "Form an SQL query to find all orders in the 'orders' table with a total amount greater than $500.",
        "Write an SQL statement to create a view that shows the total number of orders per customer from the 'orders' table.",
        "Create an SQL command to set a default value for the 'status' column in the 'orders' table.",
        "Generate an SQL query to list all employees in the 'employees' table sorted by their hire date.",
        "Formulate an SQL command to remove duplicates from the 'email_list' table.",
        "Compose an SQL query to calculate the total revenue generated from the 'sales' table.",
        "Construct an SQL statement to create an index on the 'customer_id' column of the 'orders' table.",
        "Design an SQL query to find the third highest salary in the 'employees' table.",
        "Develop an SQL command to truncate the 'log' table.",
        "Draft an SQL query to list the names of all tables in the database.",
        "Form an SQL statement to add a foreign key constraint to the 'order_id' column in the 'order_details' table.",
        "Write an SQL command to convert the 'created_at' column in the 'users' table to a different date format.",
        "Create an SQL query to retrieve the last five records added to the 'transactions' table.",
        "Generate an SQL statement to find the total number of unique products sold in the 'sales' table.",
        "Formulate an SQL command to copy data from the 'temp_data' table to the 'permanent_data' table.",
        "Compose an SQL query to find all customers who have not placed an order in the 'orders' table.",
        "Construct an SQL statement to list all columns and their data types in the 'employees' table.",
        "Design an SQL query to calculate the difference in days between the first and last orders in the 'orders' table.",
        "Write an SQL query using a WINDOW function to rank customers based on their total purchases in the 'sales' table.",
        "Create an SQL command to perform a FULL OUTER JOIN between 'employees' and 'departments' tables.",
        "Generate an SQL statement using the WITH RECURSIVE clause to create a hierarchical query in the 'organization' table.",
        "Formulate an SQL query that uses a common table expression (CTE) to summarize 'orders' table data.",
        "Compose an SQL command to create a stored procedure that inserts data into the 'logs' table.",
        "Construct an SQL query using a CROSS APPLY join to combine 'products' and 'inventory' tables.",
        "Design an SQL command to implement a trigger that audits changes in the 'employees' table.",
        "Develop an SQL query using the PIVOT function to transform rows into columns from the 'sales_data' table.",
        "Draft an SQL command to define a custom aggregate function for calculating median in the 'statistics' table.",
        "Form an SQL statement that uses a LATERAL join to correlate columns from 'orders' and 'customers' tables.",
        "Write an SQL query to implement a recursive union to find all subordinates of a manager in the 'employees' table.",
        "Create an SQL command that uses a MERGE statement to synchronize the 'backup_table' with 'main_table'.",
        "Generate an SQL statement to create a user-defined function that calculates the age from a birthdate in 'users' table.",
        "Formulate an SQL query using the EXCEPT operator to find unique records in the 'east_branch' not in 'west_branch' table.",
        "Compose an SQL command to declare and use a cursor for iterating over a result set from the 'transactions' table.",
        "Construct an SQL query that uses a CUBE operation in GROUP BY to generate grouping sets from the 'sales_report' table.",
        "Design an SQL command to create a partitioned table 'logs_archive' based on year.",
        "Develop an SQL query that uses the INTERSECT operator to find common customers in 'region1' and 'region2' tables.",
        "Draft an SQL command to create a temporary table to store intermediate results from the 'analysis' table.",
        "Form an SQL query using the ROLLUP operation to create subtotals and grand totals in 'sales_summary' table.",
        "Write an SQL statement to create a bitmap index on the 'category_id' column in the 'products' table.",
        "Create an SQL command that uses a non-correlated subquery in the WHERE clause for filtering 'orders' table.",
        "Generate an SQL statement to define a check constraint on the 'salary' column in the 'employees' table.",
        "Formulate an SQL query using a correlated subquery in the SELECT clause to calculate ranks in 'competition' table.",
        "Compose an SQL command to perform a hash join between 'customers' and 'orders' tables.",
        "Construct an SQL query using a sequence generator for auto-incrementing a primary key in the 'serial_numbers' table.",
        "Design an SQL command to create a materialized view for a complex query on the 'analytics' table.",
        "Develop an SQL query using a combination of UNION and INTERSECT to manipulate data in 'survey_results' table.",
        "Draft an SQL command to encrypt the 'sensitive_data' column in the 'clients' table.",
        "Form an SQL query that uses the LISTAGG function to concatenate string values from the 'comments' table.",
        "Write an SQL statement that performs a spatial query on the 'geolocations' table.",
        "Create an SQL command to implement a range partition on the 'historical_data' table.",
        "Generate an SQL statement using the OVERLAPS keyword to find overlapping time periods in 'reservations' table.",
        "Formulate an SQL query that uses the LEAD and LAG functions to compare sequential rows in the 'stock_prices' table.",
        "Compose an SQL command to set up a foreign data wrapper for accessing a remote 'external_data' table.",
        "Write a complex SQL query that joins five different tables ('sales', 'customers', 'products', 'employees', 'regions') and aggregates sales data by region and product category.",
        "Create an intricate SQL command to generate a monthly sales report by product, including total sales, average sales, and comparison with the previous month's sales.",
        "Generate a detailed SQL statement to extract a yearly financial summary from the 'transactions' table, showing monthly trends, highest and lowest performing months, and year-over-year growth.",
        "Formulate a multi-part SQL query to identify top-performing employees based on sales, including ranking, total sales, and percentage contribution to total company sales.",
        "Compose a complex SQL query that calculates customer lifetime value from the 'orders' and 'customers' tables, taking into account the frequency of orders, average order value, and customer acquisition date.",
        "Construct an elaborate SQL query for a product inventory report from the 'inventory' and 'products' tables, including current stock, stock value, reordering levels, and days until stock-out at current sales rates.",
        "Design a multi-step SQL command to analyze customer feedback from the 'feedback' table, categorizing comments by sentiment, identifying common themes, and linking them to specific products or services.",
        "Develop a lengthy SQL query to create a comprehensive employee performance dashboard, incorporating data from 'sales', 'employee_details', 'time_tracking', and 'customer_feedback' tables.",
        "Draft a sophisticated SQL command for a detailed analysis of marketing campaign effectiveness, correlating data from 'campaigns', 'leads', 'sales', and 'customer_demographics' tables.",
        "Form a complex SQL statement to create a dynamic pricing model, using historical sales data from the 'sales' table and external factors from the 'market_data' table.",
        "Write an extensive SQL query to conduct a thorough analysis of supply chain efficiency, utilizing data from 'suppliers', 'products', 'inventory', and 'orders' tables.",
        "Create a multi-faceted SQL command for a complete audit of data integrity across multiple tables ('customers', 'orders', 'payments', 'products'), including checks for inconsistencies and anomalies.",
        "Generate a comprehensive SQL statement for a multi-dimensional profitability analysis, incorporating data from 'sales', 'expenses', 'employee', and 'product_cost' tables.",
        "Formulate a detailed SQL query to build a risk assessment model, using data from 'transactions', 'customer_profiles', and 'market_trends' tables.",
        "Compose an advanced SQL query for a deep dive into website traffic data, correlating 'web_logs', 'user_sessions', and 'conversion' tables, with a focus on user journey and behavior patterns.",
        "Construct a complex SQL query for a longitudinal study of customer retention, using 'customer_acquisition', 'orders', and 'customer_feedback' tables.",
        "Design a multi-layered SQL command to analyze geographic sales distribution and trends, utilizing 'sales', 'customers', and 'region' tables.",
        "Develop an extended SQL query to create a detailed breakdown of operational costs, integrating data from 'expenses', 'employee', 'office', and 'equipment' tables.",
        "Draft a sophisticated SQL command to conduct a comprehensive competitor analysis, using internal 'sales' and 'product' data compared against external 'market_data' and 'competitor_sales' tables.",
        "Form a complex SQL statement to build a predictive model for stock level optimization, using historical data from 'sales', 'inventory', and 'supplier_orders' tables.",
        "Write a lengthy SQL query to create a detailed customer segmentation model, using data from 'customers', 'orders', and 'customer_feedback' tables.",
        "Create an intricate SQL command for an in-depth analysis of product return rates, correlating data from 'returns', 'customer_profiles', and 'product' tables.",
        "Generate a multi-part SQL statement for a comprehensive analysis of employee training effectiveness, using data from 'employee', 'training_sessions', and 'performance_reviews' tables.",
        "Formulate an extensive SQL query to create a detailed breakdown of e-commerce website performance, including sales conversion rates, average order value, and customer acquisition cost, using data from 'web_logs', 'sales', and 'marketing_campaigns' tables.",
    ],
    ### CSS
    "css": [
        "Create a CSS snippet to style a webpage background with a linear gradient.",
        "Write a CSS code to change the font style and size of text in a paragraph.",
        "Develop a CSS layout for a navigation menu with horizontal items.",
        "Compose CSS to create a flexbox layout with three equally spaced columns.",
        "Draft a CSS rule to apply a box-shadow effect to a div element.",
        "Formulate a CSS style for a responsive grid layout with breakpoints.",
        "Generate CSS to create a hover effect on buttons in a web page.",
        "Construct a CSS framework to style a form with aligned labels and inputs.",
        "Design a CSS animation for a fading effect on images in a slideshow.",
        "Author CSS to style a table with alternating row colors and bordered cells.",
        "Invent a CSS layout for a footer with centered text and links.",
        "Propose CSS for custom styled radio buttons and checkboxes.",
        "Form CSS to create a multi-level dropdown menu.",
        "Create a CSS snippet for a sticky header that remains at the top during scrolling.",
        "Write CSS for styling a progress bar with dynamic width based on percentage.",
        "Develop a CSS style for a modal popup with a close button.",
        "Compose a CSS rule for vertically centering content within a div.",
        "Draft CSS to create a responsive image gallery with padding and margins.",
        "Formulate CSS for custom scrollbars that are compatible across browsers.",
        "Generate a CSS layout for a sidebar with fixed width and scrollable content.",
        "Construct CSS to style a blockquote with italic font and left border.",
        "Design a CSS snippet for a responsive video embed that maintains aspect ratio.",
        "Author CSS to create a parallax scrolling effect on a webpage.",
        "Invent CSS for an accordion menu with collapsible sections.",
        "Propose a CSS style for a breadcrumb navigation bar.",
        "Form CSS for a tooltip that appears on hover over an element.",
        "Create CSS to style an image with a circular frame and border.",
        "Write a CSS snippet for a full-width background image with text overlay.",
        "Develop CSS for a flip card effect on hover in a product gallery.",
        "Compose CSS to create a three-column layout with a header and footer.",
        "Draft CSS for styling ordered and unordered lists with custom bullets.",
        "Formulate a CSS rule to apply a blur filter effect on images.",
        "Generate CSS for a responsive pricing table with different plans.",
        "Construct a CSS layout for a blog post with a featured image and sidebar.",
        "Design CSS to style an input form with validation error messages.",
        "Author CSS for creating a tabbed interface with clickable tabs.",
        "Invent CSS to style a timeline with vertical connectors and dates.",
        "Propose CSS for a responsive hero section with a call-to-action button.",
        "Form CSS to create a masonry layout for a photo gallery.",
        "Create a CSS snippet for animating a loading spinner icon.",
        "Create a CSS rule to style elements using the :nth-child pseudo-class for zebra striping.",
        "Write CSS to implement a grid layout using the CSS Grid Layout Module.",
        "Develop CSS for a text shadow effect with multiple shadows on a heading.",
        "Compose a CSS snippet to use the @font-face rule for custom web fonts.",
        "Draft CSS for a multi-background layout with layered images.",
        "Formulate CSS to apply a mix-blend-mode for blending an image with its background.",
        "Generate CSS for a clipping path effect using the clip-path property.",
        "Construct a CSS style for an object-fit property on images for different aspect ratios.",
        "Design CSS for a custom shape border using the border-image property.",
        "Author CSS to create an animated gradient background with keyframes.",
        "Invent CSS for a responsive aspect ratio box using the ::before pseudo-element.",
        "Propose CSS to style a form placeholder with the ::placeholder pseudo-element.",
        "Form CSS for a backdrop-filter effect for a frosted glass look.",
        "Create a CSS rule using the :not pseudo-class to exclude specific elements.",
        "Write CSS for a typewriter text animation effect with keyframes.",
        "Develop a CSS layout for a split-screen design with Flexbox.",
        "Compose CSS for a print-friendly version of a webpage using @media print.",
        "Draft CSS to style a page for dark mode preferences using @media (prefers-color-scheme).",
        "Formulate CSS for a variable font implementation using font-variation-settings.",
        "Generate CSS for a sticky sidebar that scrolls with the page using position: sticky.",
        "Construct CSS to style a table with CSS grid instead of traditional table tags.",
        "Design CSS to create a multi-layer hover effect using multiple :hover selectors.",
        "Author CSS for a complex animation sequence using chained animations.",
        "Invent CSS for a diagonal section divider using skewed pseudo-elements.",
        "Propose CSS to style SVG icons embedded in HTML.",
        "Form CSS for a custom animated cursor on a specific element.",
        "Create a CSS rule to implement a masonry layout without JavaScript.",
        "Write CSS for a text reveal effect on hover using CSS clip-path.",
        "Develop a CSS snippet for an interactive 3D card flip effect.",
        "Compose CSS to create a breadcrumb navigation with SVG chevron separators.",
        "Draft CSS for a custom checkbox design using the :checked pseudo-class.",
        "Formulate CSS for a rotating gallery using the perspective property.",
        "Generate CSS for an interactive image comparison slider.",
        "Construct CSS for a radial menu layout with transform properties.",
        "Design CSS for a chat bubble look with the ::after pseudo-element.",
        "Author CSS to create a continuous marquee effect using animations.",
        "Invent CSS for an expandable search bar using transitions.",
        "Propose CSS for a focus within effect using :focus-within pseudo-class.",
        "Form CSS for a stepped progress bar with custom shapes.",
        "Create CSS for a dynamic shadow effect based on element hover.",
        "Write a brief CSS snippet to change the color of all hyperlinks on hover.",
        "Create a short CSS rule to center text within a div element.",
        "Develop a concise CSS snippet for a drop shadow effect on text.",
        "Compose a minimal CSS rule to make an image circular using border-radius.",
        "Draft a brief CSS snippet to underline text on hover for emphasis.",
        "Formulate a short CSS rule for a subtle transition effect on button hover.",
        "Generate a concise CSS snippet to change the cursor to a pointer over buttons.",
        "Construct a minimal CSS rule for a linear gradient background.",
        "Design a brief CSS snippet to apply a bold style to specific words in a paragraph.",
        "Author a short CSS rule for vertically aligning an image within a div.",
        "Invent a concise CSS snippet for a text shadow to create a 3D effect.",
        "Propose a minimal CSS rule to make an element's background semi-transparent.",
        "Form a brief CSS snippet for resizing images responsively.",
        "Create a short CSS rule to rotate an element on hover.",
        "Write a concise CSS snippet for a fixed background image with scrolling content.",
        "Develop a minimal CSS rule for styling the first letter of a paragraph.",
        "Compose a brief CSS snippet for a color overlay effect on images.",
        "Draft a short CSS rule to style list items with custom bullet points.",
        "Formulate a concise CSS snippet for a hover effect that changes text color and size.",
        "Generate a minimal CSS rule for a pulsing animation on a button.",
        "Construct a brief CSS snippet to style the placeholder text of an input field.",
        "Design a short CSS rule for a border that changes color on hover.",
        "Author a concise CSS snippet for a diagonal divider between sections.",
        "Invent a minimal CSS rule to display text over an image on hover.",
        "Propose a brief CSS snippet for styling a blockquote with a left border.",
        "Form a short CSS rule for an underline that expands on hover.",
        "Create a concise CSS snippet to give a shadow to a card on hover.",
        "Write a minimal CSS rule for a smooth color transition in a gradient.",
        "Develop a brief CSS snippet to align two inline elements vertically.",
        "Compose a short CSS rule for an animated underline beneath text.",
        "Draft a concise CSS snippet for a ripple effect on button click.",
        "Formulate a minimal CSS rule for a hover effect on an image gallery.",
        "Generate a brief CSS snippet for a fade-in effect on page load.",
        "Construct a short CSS rule to style a navigation bar with active states.",
        "Design a concise CSS snippet for alternating row colors in a table.",
        "Author a minimal CSS rule for a bouncing animation on an icon.",
        "Invent a brief CSS snippet for a blurred background behind a modal.",
        "Propose a short CSS rule to change the opacity of an image on hover.",
        "Form a concise CSS snippet for a sliding drawer menu effect.",
        "Create a minimal CSS rule for a wave animation on a background.",
    ],
    ### Docker
    "docker": [
        "Write a Dockerfile to build an image for a simple Python application.",
        "Create a Docker Compose file to set up a multi-container application with a web server and database.",
        "Demonstrate how to pull an image from Docker Hub and run a container.",
        "Show the command to list all running Docker containers.",
        "Explain how to stop and remove a Docker container using its container ID.",
        "Provide an example of linking two containers in Docker.",
        "Illustrate how to create a Docker volume for persistent data storage.",
        "Describe the process of creating a Docker network for container communication.",
        "Compose a Dockerfile to set up a Node.js environment.",
        "Demonstrate how to copy files from a host to a Docker container.",
        "Create a Docker Compose file for a LAMP stack (Linux, Apache, MySQL, PHP).",
        "Show how to use environment variables in a Dockerfile.",
        "Explain how to use Docker to set up a continuous integration environment.",
        "Write a script to automate the deployment of containers using Docker.",
        "Provide an example of a multi-stage Docker build for a Java application.",
        "Illustrate the process of pushing a Docker image to a private registry.",
        "Create a health check script in a Dockerfile for a web service.",
        "Demonstrate how to scale a service with Docker Compose.",
        "Show how to update an image with a new version without downtime using Docker.",
        "Explain the use of Docker in microservices architecture.",
        "Write a Dockerfile for a Go application with a multi-stage build.",
        "Create a Docker Compose setup for a real-time chat application using WebSocket.",
        "Show the command to view logs of a Docker container.",
        "Provide a Docker command to inspect the metadata of an image.",
        "Illustrate setting up a reverse proxy using Docker.",
        "Demonstrate how to set resource limits (CPU, memory) for a container in Docker.",
        "Write a Docker Compose file for a load-balanced application with multiple replicas.",
        "Create a Dockerfile to build a Ruby on Rails application.",
        "Explain how to connect a Docker container to a database running on the host system.",
        "Show how to use Docker secrets for managing sensitive data.",
        "Provide an example of using Docker for machine learning model deployment.",
        "Illustrate how to use Docker with a CI/CD pipeline for automated testing.",
        "Create a Docker setup for a GraphQL API server.",
        "Demonstrate how to use Docker for setting up a development environment for C++ applications.",
        "Write a Docker command to prune unused images and containers to free up space.",
        "Show the process of setting up a WordPress site using Docker.",
        "Explain the role of Docker in serverless architectures.",
        "Provide a Docker solution for running batch processing jobs.",
        "Illustrate the use of Docker in IoT applications.",
        "Create a Docker Compose file for a Kafka and Zookeeper setup.",
        "Write a Dockerfile using Alpine Linux as a base image for a lightweight container.",
        "Create a Docker Compose file that uses a custom network driver.",
        "Demonstrate container orchestration with Docker Swarm.",
        "Show how to set up a Docker container to automatically restart on failure.",
        "Explain how to use Docker with a non-root user for enhanced security.",
        "Provide an example of using Docker's --init flag to handle PID 1 and signal forwarding.",
        "Illustrate how to use multi-architecture builds in Docker for cross-platform compatibility.",
        "Compose a Dockerfile to build a minimal image for a static website using Nginx.",
        "Demonstrate how to use Docker BuildKit for improved build performance.",
        "Create a Docker Compose file for an application with rolling updates and zero downtime.",
        "Show how to use Docker's health check in a Docker Compose setup.",
        "Explain how to set up a private Docker registry with authentication.",
        "Write a script to automate Docker container backups and restoration.",
        "Provide an example of setting up a cron job inside a Docker container.",
        "Illustrate how to use Docker's experimental features in a build.",
        "Create a Dockerfile to compile a C# application with .NET Core.",
        "Demonstrate how to use Docker's --squash flag to reduce the size of an image.",
        "Show how to integrate Docker with a VPN for secure container communication.",
        "Explain how to use Docker's capabilities to restrict container privileges.",
        "Write a Docker Compose file for a service mesh architecture using Istio.",
        "Create a Docker setup for a real-time data processing application using Apache Storm.",
        "Demonstrate how to use Docker to run graphical applications with a GUI.",
        "Show how to use Docker in tandem with a hardware security module (HSM).",
        "Provide a Docker solution for automated database migration management.",
        "Illustrate the setup of a Docker-based bioinformatics data analysis pipeline.",
        "Explain how to use Docker to create a reproducible research environment in academia.",
        "Create a Dockerfile to set up an Elixir/Phoenix environment with a hot code reload feature.",
        "Demonstrate the use of Docker for setting up a blockchain node.",
        "Show how to use Docker to run a TOR relay node.",
        "Provide an example of using Docker to set up a honeypot for network security.",
        "Illustrate how to use Docker for GPU-based applications using NVIDIA CUDA.",
        "Create a Docker Compose setup for a multi-tiered game server architecture.",
        "Demonstrate how to use Docker to run a full-fledged email server.",
        "Show how to set up a Docker-based remote debugging environment for software development.",
        "Explain the use of Docker in a high-performance computing (HPC) context.",
        "Write a Dockerfile for an application that uses WebAssembly.",
        "Create a Docker setup for an IoT edge computing scenario.",
        "Demonstrate how to use Docker to simulate different network conditions for testing.",
        "Show how to use Docker to create a custom static analysis toolchain.",
        "Provide a Docker-based solution for time-series data analysis using InfluxDB and Grafana.",
        "Show a command to list all Docker images on a system.",
        "Demonstrate a Docker command to remove all stopped containers.",
        "Provide a snippet to build a Docker image with a specific tag.",
        "Illustrate how to enter a running Docker container's shell.",
        "Write a Docker command to expose a port from a container to the host.",
        "Show how to set an environment variable in a Docker run command.",
        "Demonstrate how to mount a host directory into a Docker container.",
        "Provide a snippet to rename an existing Docker container.",
        "Illustrate how to inspect the network settings of a Docker container.",
        "Write a one-liner to fetch the latest version of an image from Docker Hub.",
        "Show how to view real-time events from Docker in the command line.",
        "Demonstrate a Docker command to see the history of an image.",
        "Provide a snippet to set a memory limit on a running Docker container.",
        "Illustrate a command to check the disk usage by Docker images, containers, and volumes.",
        "Write a snippet to pause and then resume a Docker container.",
        "Show how to create an anonymous volume in a Docker container.",
        "Demonstrate how to filter Docker images by label.",
        "Provide a command to set a restart policy on a container.",
        "Illustrate how to save a Docker image to a tar archive.",
        "Write a Docker command to update the image of a running container.",
        "Show a command to display the logs of a Docker container.",
        "Demonstrate how to copy a file from a Docker container to the host.",
        "Provide a snippet for running a Docker container in detached mode.",
        "Illustrate a command to attach a network to a running container.",
        "Write a one-liner to create a Docker network with a specific subnet.",
        "Show how to execute a command in a running Docker container.",
        "Demonstrate a Docker command to view the current version of Docker Engine.",
        "Provide a snippet to list all active Docker volumes.",
        "Illustrate how to restart a Docker container automatically when it exits.",
        "Write a command to follow the log output of a container.",
        "Show how to limit the CPU usage of a Docker container.",
        "Demonstrate a Docker command to create a new image from a container's changes.",
        "Provide a snippet to list the processes running in a Docker container.",
        "Illustrate how to set up an HTTP proxy for Docker.",
        "Write a command to find the IP address of a running Docker container.",
        "Show how to list all labels of a Docker image.",
        "Demonstrate a one-liner to prune all unused Docker objects.",
        "Provide a snippet to run a temporary container that removes itself on exit.",
        "Illustrate how to view the port mapping of a Docker container.",
        "Write a command to display the system-wide information of Docker.",
    ],
    ### NGINX
    "nginx": [
        "Write a basic Nginx configuration for a static website.",
        "Create an Nginx configuration to redirect HTTP to HTTPS.",
        "Draft an Nginx server block for a Python Flask application.",
        "Configure Nginx to serve multiple domains on a single server.",
        "Set up an Nginx reverse proxy for a Node.js application.",
        "Design an Nginx configuration for load balancing between two servers.",
        "Implement a basic authentication in Nginx for a protected directory.",
        "Optimize Nginx for high traffic on a WordPress site.",
        "Configure Nginx with SSL certificates for secure connections.",
        "Create a custom 404 error page in Nginx.",
        "Set up Nginx to compress responses using gzip.",
        "Write an Nginx rule to block access based on IP address.",
        "Configure Nginx as a cache server for static files.",
        "Set up Nginx to handle large file uploads.",
        "Create an Nginx configuration for a Ruby on Rails application.",
        "Implement rate limiting in Nginx to prevent abuse.",
        "Configure Nginx to serve an AngularJS application.",
        "Set up Nginx with WebSockets support for real-time communication.",
        "Create a secure Nginx configuration for an e-commerce site.",
        "Optimize Nginx performance for serving video content.",
        "Set up Nginx for a multilingual website with different subdomains.",
        "Implement a health check system in Nginx for backend services.",
        "Configure Nginx to serve a ReactJS application with client-side routing.",
        "Set up an Nginx server for a mobile application backend.",
        "Write an Nginx configuration to serve images from a CDN.",
        "Implement CORS (Cross-Origin Resource Sharing) in Nginx.",
        "Set up Nginx for a REST API with JSON responses.",
        "Configure Nginx to handle custom MIME types.",
        "Create an Nginx configuration for a microservices architecture.",
        "Optimize Nginx for SSL/TLS performance and security.",
        "Set up an Nginx server to serve static HTML, CSS, and JavaScript files.",
        "Implement HTTP/2 in Nginx for faster load times.",
        "Configure Nginx with a content security policy header.",
        "Set up Nginx for a website with user-uploaded content.",
        "Write an Nginx rule to rewrite URLs for SEO purposes.",
        "Configure Nginx to serve a Vue.js application.",
        "Implement a logging system in Nginx for debugging.",
        "Set up Nginx with a failover mechanism for high availability.",
        "Create an Nginx configuration for streaming audio content.",
        "Optimize Nginx for a cloud hosting environment.",
        "Configure Nginx to serve a GraphQL API endpoint.",
        "Set up Nginx for serving a static site with IPv6 support.",
        "Implement a WebSocket secure (WSS) proxy in Nginx.",
        "Create an Nginx configuration for an IoT device data endpoint.",
        "Configure Nginx to serve different content based on user agent.",
        "Set up Nginx to proxy a gRPC service.",
        "Implement a split testing setup using Nginx.",
        "Create an Nginx configuration for a Dockerized environment.",
        "Set up Nginx to handle real-time video streaming with HLS.",
        "Configure Nginx for a server-sent events (SSE) application.",
        "Implement a geo-blocking system in Nginx based on IP geolocation.",
        "Set up Nginx as a reverse proxy for a TOR hidden service.",
        "Create an Nginx configuration for dynamically generated PDFs.",
        "Implement a custom rate limiting strategy in Nginx for an API.",
        "Set up Nginx with a WebDAV server for file sharing.",
        "Configure Nginx to handle custom WebSocket protocols.",
        "Create an Nginx setup for a serverless architecture on AWS Lambda.",
        "Implement an Nginx configuration for MQTT protocol support.",
        "Set up Nginx to serve a progressive web app (PWA).",
        "Configure Nginx to proxy requests to a Kafka stream processor.",
        "Create an Nginx setup for a chat application with long polling.",
        "Implement a multi-tenant architecture with Nginx.",
        "Set up Nginx with QUIC protocol support for faster connections.",
        "Configure Nginx for a blockchain node's API interface.",
        "Create an Nginx configuration for an online gaming server.",
        "Implement an Nginx setup for a custom XML-based API.",
        "Set up Nginx with a two-factor authentication module.",
        "Configure Nginx to serve a decentralized application (DApp).",
        "Create an Nginx setup for a voice-over-IP (VoIP) service.",
        "Implement a content aggregation system with Nginx.",
        "Set up Nginx to serve an augmented reality (AR) application backend.",
        "Configure Nginx for dynamic content generation with Lua scripting.",
        "Create an Nginx setup for a peer-to-peer (P2P) file sharing service.",
        "Implement a blockchain explorer interface using Nginx.",
        "Set up Nginx for a virtual reality (VR) content platform.",
        "Configure Nginx to handle requests for a machine learning model API.",
        "Create an Nginx configuration for a satellite data processing service.",
        "Implement a time-based content delivery system in Nginx.",
        "Set up Nginx for a cybersecurity threat analysis platform.",
        "Configure Nginx to proxy a complex microfrontend architecture.",
        "Snippet to enable directory listing in Nginx.",
        "Nginx snippet to set up a custom log format.",
        "Configure a basic proxy_pass directive in Nginx.",
        "Set the keepalive_timeout in an Nginx server block.",
        "Snippet for setting the max upload size in Nginx.",
        "Nginx configuration to define a server name with wildcards.",
        "Set up a location block in Nginx to deny all access.",
        "Enable gzip compression for specific file types in Nginx.",
        "Configure a temporary redirect (302) in Nginx.",
        "Set custom headers in an Nginx location block.",
        "Nginx snippet to block a specific user agent.",
        "Configure SSL session caching in Nginx.",
        "Nginx configuration to add a trailing slash to URLs.",
        "Set a custom expiration for static files in Nginx.",
        "Snippet to enable HTTP/2 in Nginx.",
        "Nginx configuration for setting up a CORS policy.",
        "Define a custom error log path in Nginx.",
        "Nginx snippet to restrict access to a certain IP range.",
        "Configure a permanent redirect (301) in Nginx.",
        "Set the worker_processes directive in Nginx.",
        "Enable strict transport security in Nginx.",
        "Nginx snippet for setting cache control headers.",
        "Configure basic authentication in a location block in Nginx.",
        "Snippet to set up a custom MIME type in Nginx.",
        "Nginx configuration to disable server tokens.",
        "Set up an internal redirection in Nginx.",
        "Nginx snippet to limit the request rate.",
        "Configure a fallback error page in Nginx.",
        "Set the client_max_body_size in Nginx.",
        "Nginx snippet for proxy buffering settings.",
        "Enable SSL stapling in Nginx.",
        "Nginx configuration to adjust the buffer size.",
        "Set up a WebSocket upgrade in an Nginx server block.",
        "Nginx snippet to define a custom access log.",
        "Configure connection timeout settings in Nginx.",
        "Set up a rewrite rule in Nginx for SEO-friendly URLs.",
        "Nginx snippet to serve a specific file as a 404 error page.",
        "Configure fastcgi_pass in an Nginx PHP setup.",
        "Set the sendfile directive in Nginx.",
        "Nginx snippet to include additional configuration files.",
    ],
    ### JSON XML
    "structures": [
        "Generate a snippet representing a simple user profile with name, age, and email.",
        "Create a object for a book with fields for title, author, publication year, and genre.",
        "Write a snippet for a restaurant menu, including sections for appetizers, main courses, and desserts.",
        "Produce a structure for a movie, including title, director, release year, and cast members.",
        "Construct a snippet for a weather forecast, including date, temperature, and conditions.",
        "Generate a object for an e-commerce product, including name, price, description, and category.",
        "Create a snippet for a music album, including album name, artist, release date, and tracklist.",
        "Write a structure for a sports team, including team name, players, and coach.",
        "Formulate a snippet for a travel itinerary, including destination, dates, flights, and hotels.",
        "Design a object for a vehicle, including make, model, year, and specifications.",
        "Produce a snippet for a medical record, including patient name, date of birth, medical history, and current medications.",
        "Create a structure for an event schedule, including event names, dates, times, and locations.",
        "Write a snippet for a classroom, including teacher name, students, subjects, and timetable.",
        "Generate a object for a library catalog, including book titles, authors, ISBNs, and availability.",
        "Formulate a structure for a fitness routine, including exercises, durations, and schedule.",
        "Design a snippet for a photography portfolio, including image titles, descriptions, and dates.",
        "Create a object for a pet profile, including name, breed, age, and medical history.",
        "Write a snippet for a grocery list, including items, quantities, and categories.",
        "Construct a structure for a video game, including title, developer, platform, and storyline.",
        "Generate a object for a plant care guide, including plant names, watering schedules, and sunlight requirements.",
        "Create a snippet for a travel guide, including destinations, attractions, tips, and reviews.",
        "Write a structure for a workout log, including exercises, reps, sets, and dates.",
        "Formulate a snippet for a cooking recipe, including ingredients, steps, and cooking time.",
        "Design a object for a job posting, including title, company, description, and qualifications.",
        "Produce a snippet for a concert lineup, including artists, venues, dates, and times.",
        "Create a structure for a podcast series, including episode titles, durations, and summaries.",
        "Write a snippet for a blog post, including title, author, content, and publish date.",
        "Generate a object for a scientific experiment, including hypothesis, method, results, and conclusion.",
        "Formulate a structure for a tech gadget, including name, specifications, price, and reviews.",
        "Design a snippet for a daily journal, including date, mood, activities, and reflections.",
        "Create a object for a movie review, including title, reviewer, rating, and comments.",
        "Write a snippet for a language course, including language, levels, lessons, and materials.",
        "Construct a structure for a real estate listing, including property type, location, price, and features.",
        "Generate a object for a music festival, including line-up, dates, locations, and ticket prices.",
        "Formulate a snippet for a budget plan, including income, expenses, savings, and goals.",
        "Design a structure for a computer system, including hardware components, software versions, and performance metrics.",
        "Create a snippet for a historical event, including date, location, key figures, and significance.",
        "Write a object for a public transport timetable, including routes, times, and stops.",
        "Simple Key-Value Pair: Generate a snippet representing a person's name and age.",
        "Nested Dictionary: Create a structure representing a company, including departments and their respective employees.",
        "List of Objects: Generate a list of products, each with attributes like name, price, and quantity.",
        "Mixed Data Types: Create a snippet with mixed data types, including strings, numbers, booleans, and null.",
        "Deeply Nested Structure: Construct a object representing a book, including chapters, each with sections, paragraphs, and sentences.",
        "Large Numeric Data: Create a snippet showcasing large numeric data, such as statistical data.",
        "DateTime Formats: Generate a snippet with various date-time formats.",
        "Multilingual Text: Create a object containing text in multiple languages.",
        "Geospatial Data: Generate a snippet representing geospatial coordinates and associated information.",
        "User Profiles: Create a list of user profiles, each with multiple attributes like name, email, and preferences.",
        "Configuration Settings: Generate a object representing configuration settings for a software application.",
        "API Response Simulation: Create a snippet simulating an API response with status, message, and data fields.",
        "E-commerce Cart: Generate a object representing an e-commerce shopping cart with items, prices, and quantities.",
        "Event Scheduling: Create a structure for event scheduling, including event details, participants, and times.",
        "Educational Course Data: Generate a snippet with course data, including course name, description, and modules.",
        "Health Records: Create a object representing patient health records with personal details and medical history.",
        "Social Media Feed: Generate a list representing a social media feed, including posts, comments, and likes.",
        "Travel Itinerary: Create a structure for a travel itinerary, including destinations, accommodations, and activities.",
        "Financial Transactions: Generate a snippet for financial transactions, including date, amount, and category.",
        "Weather Data: Create a object representing weather data, including temperature, humidity, and forecasts.",
        "Recipe and Ingredients: Generate a snippet for a recipe, including ingredients, quantities, and steps.",
        "Sport Match Summary: Create a structure summarizing a sports match, including teams, scores, and key events.",
        "Vehicle Information: Generate a object for vehicle information, including make, model, and specifications.",
        "Generate a snippet representing a configuration file for a web server with nested settings.",
        "Create a snippet that defines a multi-level menu for a website, including headers and subheaders.",
        "Produce a snippet describing a complex data structure with multiple nested dictionaries.",
        "Write a snippet for a book catalog, including a list of books with their details like author, title, and publication year.",
        "Generate a snippet for a movie database, including a list of movies with properties like director, release date, and genre.",
        "Create a snippet representing an employee directory, with each employee having multiple attributes.",
        "Formulate a snippet for a recipe book, including various recipes with ingredients and steps.",
        "Generate a snippet that represents a complex workflow with multiple stages and dependencies.",
        "Write a snippet for a scientific dataset, including metadata and data structure.",
        "Create a snippet to define a user interface layout with nested components.",
        "Develop a snippet representing a network configuration with various devices and their settings.",
        "Generate a snippet for a classroom setup, including a list of students, teachers, and courses.",
        "Formulate a snippet describing a travel itinerary with multiple destinations and activities.",
        "Create a snippet for a music library, including albums, artists, and song lists.",
        "Generate a snippet representing a sports tournament, including teams, players, and match schedules.",
        "Write a snippet for a health record system, including patient details, treatments, and medical history.",
        "Create a snippet that defines a complex project plan with tasks, milestones, and resources.",
        "Generate a snippet for an automotive catalog, including a list of cars with their specifications.",
        "Formulate a snippet describing a retail inventory, including products, categories, and prices.",
        "Write a snippet for a zoo's animal inventory, including species, habitats, and feeding schedules.",
        "Generate a snippet representing a TV series collection, with seasons, episodes, and cast.",
        "Create a snippet for a personal budget, including income sources, expenses, and savings goals",
    ],
    # HTML
    "markup": [
        "Create a personal blog page with a biography section.",
        "Design a recipe webpage with ingredients and steps listed.",
        "Develop a simple quiz application interface.",
        "Construct a product landing page with images and descriptions.",
        "Implement a feedback form with multiple input types.",
        "Generate a news article page with headlines and text.",
        "Build a portfolio gallery showcasing various projects.",
        "Create a weather forecast display with icons and data.",
        "Design a movie review section with star ratings.",
        "Develop a contact information page with social media links.",
        "Construct an event invitation with time, date, and location.",
        "Implement a FAQ section with expandable answers.",
        "Generate a travel blog entry with photos and captions.",
        "Build a restaurant menu with categories and prices.",
        "Create a classroom schedule display.",
        "Design a fitness tracker interface with graphs.",
        "Develop a real estate listing page with property details.",
        "Construct an online store homepage with featured products.",
        "Implement a tech news feed with article summaries.",
        "Generate a music album review page.",
        "Build a scientific research article display with references.",
        "Create a public transport timetable display.",
        "Design a pet adoption profile page with images and descriptions.",
        "Develop a digital art portfolio.",
        "Construct a podcast episode list with audio links.",
        "Implement a book summary page with author bio.",
        "Generate a historical timeline with dates and events.",
        "Build a workout routine page with exercises listed.",
        "Create a gardening tips blog post.",
        "Design a coding tutorial page with code snippets.",
        "Develop a DIY project instructions page.",
        "Construct a travel packing checklist.",
        "Implement a language learning resource list.",
        "Generate a photography tips page with example images.",
        "Build a personal finance advice blog entry.",
        "Create a local event calendar.",
        "Design a video game review with screenshots.",
        "Develop a car maintenance guide.",
        "Construct a home decoration ideas page.",
        "Implement a plant care guide with specific plant profiles.",
        "Create a personal blog page header using non-standard alignment.",
        "Design a recipe webpage footer with a unique list format.",
        "Develop a quiz interface using conditional visibility elements.",
        "Construct a product landing page with an unconventional navigation bar.",
        "Implement a feedback form using rarely used input types.",
        "Generate a news article page with a multi-column layout.",
        "Build a portfolio gallery using dynamic image resizing.",
        "Create a weather forecast display incorporating animation.",
        "Design a movie review section with custom star rating graphics.",
        "Develop a contact page using embedded maps in an unusual way.",
        "Construct an event invitation with interactive date and time selectors.",
        "Implement a FAQ section with collapsible content using unique identifiers.",
        "Generate a travel blog entry with integrated video and text.",
        "Build a restaurant menu using table layouts in a creative way.",
        "Create a classroom schedule with hover-over details.",
        "Design a fitness tracker interface incorporating SVG graphics.",
        "Develop a real estate listing with interactive image galleries.",
        "Construct an online store using advanced design features.",
        "Implement a tech news feed with a toggle for different themes.",
        "Generate a music album review page using audio controls.",
        "Build a scientific article display with complex citation formatting.",
        "Create a public transport timetable using time zone conversions.",
        "Design a pet adoption profile with interactive slideshows.",
        "Develop a digital art portfolio with a color theme switcher.",
        "Construct a podcast list using custom audio players.",
        "Implement a book summary page with nested lists.",
        "Generate a historical timeline with scroll-triggered animations.",
        "Build a workout routine page with expandable sections.",
        "Create a gardening blog post with embedded timelapse videos.",
        "Design a coding tutorial with live editable code snippets.",
        "Develop a DIY project page using step progress indicators.",
        "Construct a travel checklist with interactive checkboxes.",
        "Implement a language learning resource list with multilingual support.",
        "Generate a photography tips page with custom image filters.",
        "Build a personal finance blog with interactive charts.",
        "Create an event calendar with recurring events functionality.",
        "Design a video game review with a parallax scrolling effect.",
        "Develop a car maintenance guide with accordion-style content.",
        "Construct a home decoration ideas page with a 3D view feature.",
        "Implement a plant care guide with a seasonal advice filter.",
    ],
}

if __name__ == "__main__":
    all_langs = list(languages.keys())
    for lang in all_langs:
        res = get_code(lang, limit=None, save_root="../../datasets/llama/tasks")
